services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpass
      POSTGRES_DB: pets
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
  
  web:
    image: amandabral9954/image-app:latest
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
    depends_on:
      - db 


volumes:
  pg-data:

