kind: Deployment 
apiVersion: apps/v1 
metadata:
   name: nodejs-deployment
   namespace: nodejs-image-app 
   labels: 
     app: nodejs 
spec:
    replicas: 2 
    selector: 
      matchLabels:
        app: nodejs
        env: test
        tier: frontend
    template:
      metadata:
        name: nodejs-pod
        labels: 
          app: nodejs 
          env: test
          tier: frontend 
      spec:
        containers:
          - name: nodejs-container
            image: amandabral9954/image-app:1.0
            ports:
              - containerPort: 3000
            resources:  
               requests:
                  memory: "256Mi"
                  cpu: "250m" 
               limits:
                  memory: "512Mi"
                  cpu: "500m"
            env:
              - name: DB_HOST
                value: "postgresql-service"
              - name: DB_USER
                value: "dockeruser"
              - name: DB_PASSWORD
                value: "dockerpass" 
              - name: DB_NAME
                value: "pets" 
             
