kind: Service 
apiVersion: v1 
metadata: 
  name: postgresql-service 
  namespace: nodejs-image-app
spec:
  selector:
    app: postgresql 
    env: test
    tier: backend 
  type: ClusterIP
  ports:
    - protocol: TCP 
      port: 5432
      targetPort: 5432
      name: postgres 
